# Generated by Django 4.2.6 on 2023-11-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slider_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='cover',
            field=models.ImageField(upload_to='input/'),
        ),
    ]
