# Generated by Django 4.2.6 on 2023-11-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seam', '0002_image_slider_value_alter_image_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='slider_value',
        ),
    ]
